# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed0fe139c06f5d4188a83b096ba29c08fa7754c250ec845c56c97fd790ddacc3bc9d68a1659e1ea239cde3a1c8c249ac076976dbf97f9a2da191fc718cb95feb

test:
  secret_key_base: a938f4fe745bb2bc72aee53d162fd1312e9a573f13cec0201de8a0b2a68b851a39e1c8f7b0af9bb96a06177c679c6d2f77494b9e9200a3e30afe51ccdc90a456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
